### ISSUE TITLE
Recent automated commits only contain changes to python cache files 

### ISSUE THREAD

**Issue by defgsus** [Cheltenham-Open-Data/food-bank#2]
... which should not be part of a repository.

https://github.com/Cheltenham-Open-Data/food-bank/commits/main/python/__pycache__

The `.gitignore` should simply contain `__pycache__/` and `*.pyc* to exclude all those files. 

To remove the files from future commits, you need to delete them and commit the deletion.

Cheers

**Comment by MatBenfield** [comment]
thanks
